name: "Build"
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NPM_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
    - uses: actions/checkout@v1
      with:
        persist-credentials: false
    - uses: actions/setup-node@v2
      with:
        node-version: '12.x'
    - run: npm install
    - run: npm test
    - run: npx semantic-release
      if: github.ref == 'refs/heads/master'
